### PR TITLE
Fix Slovak language typos

### PR DESCRIPTION
**Pull request by TheGameSpider**

### CODE REVIEW

**Comment by Pyker** [comment]
This PR has no description whatsoever... What did you fix?

**Comment by TheGameSpider** [comment]
> This PR has no description whatsoever... What did you fix?

[screenshots on imgur](https://imgur.com/a/ij5p9Hy)

**Comment by Pyker** [comment]
You're editing the wrong file (it was renamed to `UIText_sk.properties` in this repo). I can manually apply the changes to the file, but for this PR to be merged I would need the changes to be made to the right file. I'm not sure, but renaming it might work.

**Comment by Pyker** [comment]
Thank you for your contribution! 👍

**Pull request merged**
