### PR TITLE
Microsoft acccount login

### PR DESCRIPTION
**Pull request by balika011**

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Just going to add in some comments here.

Yesterday there was some discussion in the MultiMC Discord with Peterix who is a Mojang developer and works on the launcher and has been working on the auth solution.

https://discord.com/channels/132965178051526656/134843027553255425/790346146772942868

My own TLDR is below, but I suggest you look through and make your own analysis on the discussion:

- This current setup using OAuth may be in violation of ToS. Although that was not made clear in the conversation, it was just `you are on thin ice if you use that` and doesn't follow Microsoft rules and could very easily be C&Ded
- There is no official api at the moment, so that's inferring that using this now is completely not official
- OAuth is not the solution, it may work, but it's not an OAuth system
- The system will probably involve Microsoft approving third party clients in order to access this system with some sort of agreement between tools and MS/Mojang, but they're still figuring this out, but from the sounds of it anyone wanting to provide Microsoft account logins for Minecraft will need to be approved by Microsoft
- Clients should be registering an application with Azure and not using the vanilla launchers client id as it looks like you've done

Given all this information, I made the decision to keep my implementation of MS account support until Microsoft/Mojang officially say otherwise and ask for it to be taken down (or forcefully remove the Azure application)

Happy to have discussions here if needed or over Discord (RyanTheAllmighty#0850) as we're all affected by this and the discussion yesterday is slightly worrying

**Comment by balika011** [comment]
[Authentication with the Live Connect endpoint](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-live-connect?view=bingads-13)
There is official documentation and the only use case is to make sure you own a legitimate copy of the game.
How could that possibly be violation of ToS?

**Comment by RyanTheAllmighty** [comment]
> [Authentication with the Live Connect endpoint](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-live-connect?view=bingads-13)
> There is official documentation and the only use case is to make sure you own a legitimate copy of the game.
> How could that possibly be violation of ToS?

Like I said, that's what I took away from the conversation. What you read in that conversation may be different to me. While the words of it breaking ToS wasn't specifically acknowledged, the words "thin ice" were used and specifically C&D's were mentioned.

The truth is nobody knows as this is partially reverse engineered. The OAuth side is documented and fine, but the interactions with the Minecraft api's are not and they were reverse engineered, so the legality of using those as a third party are the same as using the Mojang legacy login api's through the years. Mojang have been  "okay" with that, but now were involving Microsoft and their api's, and with Microsoft being 100% quiet on this (other than saying they're working on something) we can't know for sure

**Comment by balika011** [comment]
I did the homework to read the agreements.
The ToS you are referring to is between Mojang and Microsoft. We have nothing to do with it.
We have to comply to Mojang's terms.
Mojang gives us the right to reverse engineer the game. This includes the launcher too, meaning we can reverse the ownership validation and replicate the functionality.

Of curse Mojang may or may not violate Microsoft's ToS and the worst case that could happen that affects us is Minecraft gets banned. That's not going to happen.

**Pull request merged**
